### ISSUE TITLE
Derrivative work

### ISSUE THREAD

**Issue by renzenicolai** [electroniceel/protoboard#8]
Hello Electroniceel!

Thank you for making such a great prototyping board :-)

I've got a question about using your protoboard design in a small run of boards for an event we're organising. We plan on handing them out as nametags/badges with a prototyping area.

How would you like to be credited? Is a mention on the page on our website about the board okay with you or would you like to be mentioned in the silkscreen of the board itself?

Greetings,
Renze Nicolai
(https://github.com/badgeteam / https://badge.team)

**Comment by electroniceel** [comment]
> I've got a question about using your protoboard design in a small run of boards for an event we're organising. We plan on handing them out as nametags/badges with a prototyping area.

Nice idea

> How would you like to be credited? Is a mention on the page on our website about the board okay with you or would you like to be mentioned in the silkscreen of the board itself?

I'd appreciate it if you link to this github repo, so that anyone interested can easily find it, make their own variant or send pull requests. You can either use the full url or the shortener http://git.io/vNUDX.

It would be ok if you do that on your website about the board. If you got plenty of free space on the back or something like that, you could also put it on the silkscreen. But I won't be angry if it doesn't fit and you just have it on the website.

Have fun with your event!
